version: "3.9"
services:
  dbserver:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: default
    ports:
      - 3306:3306
    restart: on-failure
